### ISSUE TITLE
Rename `upsertChains` to `insertChains`

### ISSUE THREAD

**Issue by ThibaudDauce** [Cosmian/cosmian_java_lib#37]
Right now there is `upsertEntries` and `upsertChains` but the two callbacks are really different (not the same return value and not the same locking required). `upsertChains` should be `insertChains` since we're guaranteed that the given chains are new. `cloudproof_js` use these names. Rust `findex` use `upsert_entry` and `insert_chain` (not a big fan of the singular here)

**Comment by Manuthor** [comment]
has been done in version 7.0.0
